#+PROPERTY: header-args:R   :cache yes :session readme-r :results value :exports both
#+OPTIONS: toc:nil
#+TITLE: Inserting references in Rd and roxygen2 documentation

#+BEGIN_EXPORT html
[![CRANStatusBadge](http://www.r-pkg.org/badges/version/Rdpack)](https://cran.r-project.org/package=Rdpack)
[![CRAN RStudio mirror downloads](https://cranlogs.r-pkg.org/badges/Rdpack)](https://www.r-pkg.org/pkg/Rdpack)
[![DOI](https://zenodo.org/badge/100482670.svg)](https://zenodo.org/badge/latestdoi/100482670)
#+END_EXPORT
# Removing this, since doesn't seem to be updated anymore:
# [![rpackages.io rank](http://www.rpackages.io/badge/Rdpack.svg)](http://www.rpackages.io/package/Rdpack)
#
# Saw these badges in Rcpp/README but they don't work for Rdpack
# [![CRAN use](https://jangorecki.gitlab.io/rdeps/Rdpack/CRAN_usage.svg?sanitize=true)](https://cran.r-project.org/package=Rdpack)
# [![CRAN indirect](https://jangorecki.gitlab.io/rdeps/Rdpack/indirect_usage.svg?sanitize=true)](https://cran.r-project.org/package=Rdpack)
# [![BioConductor use](https://jangorecki.gitlab.io/rdeps/Rdpack/BioC_usage.svg?sanitize=true)](https://cran.r-project.org/package=Rdpack)


Rdpack provides functions for manipulation of R documentation objects, including functions
=reprompt()= and =ereprompt()= for updating existing Rd documentation for functions, methods
and classes; Rd macros for citations and import of references from =bibtex= files for use in
=Rd= files and =roxygen2= comments (=\insertRef=, =\insertCite=, =\insertAllCited=); Rd
macros for evaluating and inserting snippets of R code and the results of its evaluation
(=\printExample=) or creating graphics on the fly (=\insertFig=); and many functions for
manipulation of references and Rd files.

#+BEGIN_SRC R :results value silent :exports none
library(Rdpack)
#+END_SRC

#+TOC: headlines

* Installing Rdpack

Install the  [[https://cran.r-project.org/package=Rdpack][latest stable version]] from CRAN:
#+BEGIN_EXAMPLE
install.packages("Rdpack")
#+END_EXAMPLE


You can also install the [[https://github.com/GeoBosh/Rdpack][development version]] of =Rdpack= from Github:
#+BEGIN_EXAMPLE
library(devtools)
install_github("GeoBosh/Rdpack")
#+END_EXAMPLE



* Inserting Bibtex references and citations

The simplest way to insert Bibtex references is with the Rd macro =\insertRef=.
Just put =\insertRef{key}{package}= in the documentation to insert item with key
=key= from file =REFERENCES.bib= in your package =package=. Alternatively, use
one or more =\insertCite{key}{package}= commands to cite works from
=REFERENCES.bib=, then issue a single =\insertAllCited{}= directive to produce a
list of all cited references. For this to work
the =DESCRIPTION= file of the package needs to be amended, see below the full
details. 


** Preparation 

To prepare a package for importing BibTeX references it is necessary to tell the
package management tools that package Rdpack and its Rd macros are needed. The
references should be put in file =inst/REFERENCES.bib=.  These steps are
enumerated below in somewhat more detail, see also the vignette
[[https://cran.r-project.org/package=Rdpack][=Inserting_bibtex_references=]].


1. Add the following lines to  file "DESCRIPTION":
   #+BEGIN_EXAMPLE
   Imports: Rdpack
   RdMacros: Rdpack
   #+END_EXAMPLE
   Make sure the capitalisation of =RdMacros:= is as shown. If the field
   =RdMacros:= is already present, add "Rdpack" to the list on that
   line. Similarly for field "Imports:".

2. Add the following line to file "NAMESPACE":
   #+BEGIN_EXAMPLE
   importFrom(Rdpack,reprompt)
   #+END_EXAMPLE

   #+RESULTS:

   The equivalent line for =roxygen2= is 
   #+BEGIN_EXAMPLE
   #' @importFrom Rdpack reprompt
   #+END_EXAMPLE

   #+RESULTS:

3. Create file =REFERENCES.bib= in subdirectory =inst/= of your package and
   put the BibTeX references in it.

# -------------


** Inserting references

Once the steps outlined above are done, references can be inserted in the
documentation as
#+BEGIN_EXAMPLE
\insertRef{key}{package}
#+END_EXAMPLE
where =key= is the bibtex key of the reference and =package= is your package.
This works in =Rd= files and in =roxygen= documentation chunks.

Usually references are put in section =references=. In an =Rd= file this might look
something like:
#+BEGIN_EXAMPLE
\references{
\insertRef{Rdpack:bibtex}{Rdpack}

\insertRef{R}{bibtex}
}
#+END_EXAMPLE
The equivalent =roxygen2= documentation chunk would be:
#+BEGIN_SRC R
#' @references
#' \insertRef{Rpack:bibtex}{Rdpack}
#'
#' \insertRef{R}{bibtex}
#+END_SRC

The first line above inserts the reference with key =Rpack:bibtex= in Rdpack's
REFERENCES.bib. The second line inserts the reference labeled =R= in file
REFERENCES.bib from package =bibtex=. 

The example above demonstrates that references from other packages can be
inserted (in this case =bibtex=), as well. This is strongly discouraged for
released versions but is convenient during development. One relatively safe use
is when the other package is also yours - this allows authors of multiple
packages to not copy the same refences to each of their own packages.
 
For further details see the vignette 
[[https://cran.r-project.org/package=Rdpack][=Inserting_bibtex_references=]]
or open it from =R=:
#+BEGIN_EXAMPLE
vignette("Inserting_bibtex_references", package = "Rdpack")
#+END_EXAMPLE
(The latest version of the vignette is at
[[https://github.com/GeoBosh/Rdpack/blob/master/vignettes/Inserting_bibtex_references.pdf][=Inserting_bibtex_references (development version on github)=]].)

# ---------


** Inserting citations

From version 0.6-1 of "Rdpack", additional Rd macros are available for
citations.  They can be used in both Rd and roxygen2 documentation.

=\insertCite{key}{package}= cites =key= and records it for use by
=\insertAllCited=, see below. =key= can contain more keys separated by commas.
  
=\insertCite{parseRd,Rpack:bibtex}{Rdpack}= produces 
src_R[:exports results :results value raw]{insert_citeOnly("parseRd,Rpack:bibtex", "Rdpack")}
and 
=\insertCite{Rpack:bibtex}{Rdpack}=         gives
src_R[:exports results :results value raw]{insert_citeOnly("Rpack:bibtex", "Rdpack")}.


By default the citations are parenthesised: =\insertCite{parseRd}{Rdpack}= produces
src_R[:exports results :results value raw]{insert_citeOnly("parseRd", "Rdpack")}.  To get
textual citations, like 
src_R[:exports results :results value raw]{insert_citeOnly("parseRd;textual", "Rdpack")}, 
put the string =;textual= at the end of the key. The references in the last two sentences
would be produced with =\insertCite{parseRd}{Rdpack}= and
=\insertCite{parseRd;textual}{Rdpack}=, respectively.  This also works with several
citations, e.g.

=\insertCite{parseRd,Rpack:bibtex;textual}{Rdpack}= produces:
src_R[:exports results :results value raw]{insert_citeOnly("parseRd,Rpack:bibtex;textual", "Rdpack")}.

The macro =\insertNoCite{key}{package}= records one or more
references for =\insertAllCited= but does not cite it. Setting
=key= to =*= will include all references from the
specified package. For example, 
=\insertNoCite{R}{bibtex}=  and  =\insertNoCite{*}{utils}=
record the specified references for inclusion by =\insertAllCited=. 

=\insertAllCited= inserts all references cited with
=\insertCite= or =\insertNoCite=. Putting this macro
in the references section will keep it up to date automatically. 
The Rd section may look something like:
#+BEGIN_EXAMPLE
    \insertAllCited{}
#+END_EXAMPLE
or, in roxygen2, the references chunk might look like this:
#+BEGIN_EXAMPLE
    #' @references
    #'     \insertAllCited{}
#+END_EXAMPLE

To mix the citations with other text, such as ``see also'' and ``chapter 3'',
write the list of keys as a free text, starting it with the symbol =@= and
prefixing each key with it.  The =@= symbol will not appear in the output. For
example, the following code
#+BEGIN_EXAMPLE
  \insertCite{@see also @parseRd and @Rpack:bibtex}{Rdpack}
  \insertCite{@see also @parseRd; @Rpack:bibtex}{Rdpack}
  \insertCite{@see also @parseRd and @Rpack:bibtex;textual}{Rdpack}
#+END_EXAMPLE
produces:

  src_R[:exports results :results value raw]{insert_citeOnly("@see also @parseRd and @Rpack:bibtex", "Rdpack")} 

  src_R[:exports results :results value raw]{insert_citeOnly("@see also @parseRd; @Rpack:bibtex", "Rdpack")} 

  src_R[:exports results :results value raw]{insert_citeOnly("@see also @parseRd and @Rpack:bibtex;textual", "Rdpack")}

---

=\insertCiteOnly{key}{package}= is as =\insertCite= but does not include the key
in the list of references for =\insertAllCited=.



** Changing the style of references

Bibliography styles for lists of references are supported from _Rdpack (>=
0.8)_. Currently the only alternative offered is to use long names (Georgi
N. Boshnakov) in place of the default style (Boshnakov GN). More comprehensive
alternatives can be included if needed or requested.

To cause all lists of references produced by ~\insertAllCited~ in a package to appear with
full names, add ~.onLoad()~ function to your package. If you don't have ~.onLoad()~, just
copy the following definition: 
#+BEGIN_SRC R
    .onLoad <- function(lib, pkg){
        Rdpack::Rdpack_bibstyles(package = pkg, authors = "LongNames")
        invisible(NULL)
    }
#+END_SRC

If you already have ~.onLoad()~, add the line containing the
~Rdpack::Rdpack_bibstyles~ call to it.

After installling/reloading your package the lists of references should appear
with long author names. "Rdpack" itself now uses this style.



** Troubleshooting

*** A puzzling message in devtools development mode
The described procedure works transparently in =roxygen2= chunks and with Hadley
Wickham's package =devtools=.  Packages are built and installed properly with
the =devtools= commands and the references are processed as expected.

Currently (2017-08-04) if you run help commands =?xxx= for functions from the
package you are working on /in developement mode/ and their help pages contain
references, you may encounter some puzzling warning messages, something like:
#+BEGIN_EXAMPLE
    1: In tools::parse_Rd(path) :
      ~/mypackage/man/abcde.Rd: 67: unknown macro '\insertRef'
#+END_EXAMPLE
These warnings are harmless and can be ignored --- the help pages are built
properly and no warnings appear outside /developer's mode/, e.g. in a separate R
session[fn:whathappens]. Even better, use the function =viewRd()= described
below to view the required help file.

[fn:whathappens] If you care, here is what happens.  These warnings appear
because =devtools= reroutes the help command to process the developer's Rd
sources (rather than the documentation in the installed directory) but doesn't
tell =parse_Rd= where to look for additional macros. Indeed, the message above
shows that the error is in processing a source Rd file in the development
directory of the package and that the call to =parse_Rd= specifies only the
file.


*** Typical errors

The functions underlying the processing of references and citations intercept
errors, such as missing BibTeX labels or badly formed items in REFERENCES.bib,
and issue informative warnings during the building and installation of the
package, so that the developer is alerted but the package can still be built and
installed. In these cases the functions usually insert a suitable text in the
documentation, as well. If you encounter a situation contradicting this
description, it is probably a bug --- please report it (but check first for the
typical errors listed below).

A non-decipherable error message is probably caused by one of the following 
typical errors:

- misspelled =RdMacros:= field in file DESCRIPTION. The safest way to avoid this
  is to copy it from the DESCRIPTION file of a working package.

- omitted second argument of a reference or citation macro. Most of these macros
  have the package name as a second argument.

These errors occur during parsing of the Rd files, before the control is passed
to the =Rdpack='s macros. 



** Latex markup in BibTeX entries

In principle, BibTeX entries may contain arbitrary Latex markup, while the Rd format
supports only a subset. As a consequence, some BibTeX entries may need some editing when
included in REFERENCES.bib[fn:6]. Only do this for entries that do not render properly or
cause errors, since most of the time this should not be necessary.

If mathematics doesn't render properly replace the Latex dollar syntax with Rd's ~\eqn~,
e.g. ~$x^2$~ with ~\eqn{x^2}~. This should not be needed for versions of Rdpack
0.8-4 or later. 

Some Latex macros may have to be removed or replaced with suitable Rd markup. Again,
do this only if they cause problems, since some are supported, e.g. ~\doi~.

See also the overview help page, ~help("Rdpack-package")~, of package ="Rdpack"=. 
Among other things, it contains some dummy references which illustrate the above.



[fn:6] Thanks to Michael Dewey for suggesting the discussion of this.


** Encoding of file REFERENCES.bib

If a package has a declared encoding (in file =DESCRIPTION=), =REFERENCES.bib= is read-in
with that encoding[fn:enc].  Otherwise, the encoding of =REFERENCES.bib= is assumed to be
UTF-8 (which includes ASCII as a subset).

Note that BibTeX entries downloaded from online databases and similar sources may contain
unexpected characters in other encodings, e.g. 'latin1'. In such cases the check tools in
R-devel (since about 2018-10-01) may give warnings like:
#+BEGIN_EXAMPLE
    prepare_Rd: input string 1 is invalid in this locale
#+END_EXAMPLE
To resolve this, convert the file to the declared encoding or UTF-8. Alternatively, replace
the offending symbols with their classic TeX/LaTeX equivalents (which are ASCII). Non-ASCII
symbols in BibTeX entries obtained from online databases are often in fields like "Abstract",
which are normally not included in lists of references and can be deleted from REFERENCES.bib.

One way to check for non-ASCII symbols in a file is =tools::showNonASCIIfile()=.

Internally, LaTeX sequences standing for accented Latin characters, such as =\'e= and =\"o=,
are converted to UTF-8.  So, even if the file REFERENCES.bib is pure ASCII, it may implicitly
give raise to non-ASCII characters. This may cause R's checking tools to complain about
non-ASCII characters even after it has been verified that there are none. If this happens,
add the encoding declaration to file DESCRIPTION[fn:enc2]:
#+BEGIN_EXAMPLE
Encoding: UTF-8
#+END_EXAMPLE
Needless to say, make sure that there are really no characters from encodings like 'latin1'.


[fn:enc] From =Rdpack (>=0.9-1)= The issue of not handling the encoding was raised by
Professor Brian Ripley.

[fn:enc2] Admittedly, this is not ideal since the user should not need to care how things are
processed internally but I haven't pinpointed the exact cause for this.



* Viewing Rd files

A function, =viewRd()=, to view Rd files in the source directory of a package
was introduced in version 0.4-23 of =Rdpack=. A typical user call would look
something like:
#+BEGIN_EXAMPLE
Rdpack::viewRd("./man/filename.Rd")
#+END_EXAMPLE
By default the requested help page is shown in text format. To open the page in
a browser, set argument 'type' to "html":
#+BEGIN_EXAMPLE
    Rdpack::viewRd("./man/filename.Rd", type = "html")
#+END_EXAMPLE
=viewRd()= renders references and citations correctly, since it understands Rd macros.

Users of 'devtools' can use =viewRd= in place of =help()= to view rendered Rd
sources in development mode. This should work also in development mode on any
platform (e.g. RStudio, Emacs/ESS, Rgui).
# (Yes, the real roxygen2 sources are the **.R** files but
# =devtools::document()= transfers the roxygen2 documentation chunks to Rd files,
# and a few others, which are then rendered by =R='s tools.)

 









* Using Rdpack::reprompt()

** What it does

=Rdpack::reprompt()= updates =Rd= documentation. In the most common case when it
is called on an =Rd= file, it updates the documentation of all functions,
methods and classes documented in the file. For functions this includes
updating the usage section, adding missing aliases and =\item='s for arguments
not described yet. For methods and classes entries for new methods and slots
are updated in a similar way. See the documentation for details.

=Rdpack::reprompt()= can also be invoked on an object or the name of an object,
just as =utils::prompt=. In that case it checks for installed documentation for
the object and works on it if found. Otherwise it creates an =Rd= file with
initial content similar to the one generated by =utils::prompt= but modified
so that the package can be built.

If a new function, say =newfun= is to be documented in an existing Rd file, just add
=newfun()= to the usage section in the file and call =Rdpack::reprompt()= to insert the
correct usage statement, add an alias, and add items for any new arguments. Put quotes around
the function name if it is non-syntactic.  For replacement functions (functions with names
ending in =<-=) ~reprompt()~ will insert the proper usage statement. For example, if the
signature of =xxx<-= is =(x, ..., value)=, then both, ="xxx<-"()= and =xxx() <- value= will
be replaced by =xxx(x, ...) <- value=.

=Rdpack::reprompt()= *does not remove* anything that has become obsolete 
but it alerts the user to remove aliases, methods, and descriptions of arguments
that have been removed. 

** Reprompt and open in an editor

To open the =reprompt()=-ed file, argument =edit= can be used.  For this to
work, =options("editor")= needs to be set suitably but it usually is.  If ~edit
= TRUE~, then =Rdpack::reprompt()= will open the Rd file in an editor.  For more
convenient access to this feature, use =Rdpack::ereprompt()= (edit reprompt),
which calls =Rdpack::reprompt()= with ~edit = TRUE~ and sets the output filename
to be the same as the input filename.


In RStudio, =reprompt()= can be invoked on the =Rd= file being edited or the
selected name of an object in a source code file using RStudio add-in
=Repropmpt= (contributed by Duncan Murdoch). Obviously, this makes sense only
for Rd files not generated by =roxygen2=.

In Emacs/ESS there are various ways to use =Rdpack::reprompt()= and
=Rdpack::ereprompt()=. If =options("editor")= is set to =emacsclient=,
=Rdpack::ereprompt= is one option. It can also be assigned to a key (wrapped in
Elisp code), for example to be invoked on the currently edited file. Such a
function and example key binding can be found at [[https://github.com/GeoBosh/georgisemacs][georgisemacs]].




* Inserting evaluated examples

=Rdpack= provides a macro that takes a chunk of R code, evaluates it, and includes both the code and
the results in the rendered documentation. The layout is similar to that in the R console but
the code is not prefixed with anything and the output is prefixed with comment symbols.
For example,
#+BEGIN_EXAMPLE
    \printExample{2+2; a <- 2*3; a}
#+END_EXAMPLE 
gives
#+BEGIN_EXAMPLE
    2 + 2
    ##: 4
    a <- 2 * 3
    a
    ##: 6
#+END_EXAMPLE
The help page of ~?Rdpack::promptUsage~ contains a number of examples created with
~\printExample~. The corresponding Rd file can be obtained from the package tarball or from
https://github.com/GeoBosh/Rdpack/blob/master/man/promptUsage.Rd. 

Vignette [[https://github.com/GeoBosh/Rdpack/blob/master/vignettes/Inserting_figures_and_evaluated_examples.pdf][=Inserting_figures_and_evaluated_examples=]] gives further details.

** Evaluating the examples in section Examples

The macro ~\runExamples~ can be used as a replacement of section ~examples~.  For example, if
the following code is put at the top level in an Rd file (i.e. not in a section):
#+BEGIN_EXAMPLE
    \runExamples{2+2; a <- 2*3; a}
#+END_EXAMPLE 
then it will be evaluated and replaced by a normal section examples:
#+BEGIN_EXAMPLE
    \examples{
    2 + 2
    ##: 4
    a <- 2 * 3
    a
    ##: 6
    }
#+END_EXAMPLE
This generated examples section is processed by the standard R tools (almost) as if it was
there from the outset. In particular, the examples are run by the R's quality control tools
and tangled along with examples in other documentation files[fn:runExamples]. A small example package
using this feature is at [[https://github.com/GeoBosh/reprexes/tree/master/runExamplesCheck][runExamplesCheck]].
 
[fn:runExamples] In versions of ~R~ before =3.6.0=  the macro ~\runExamples~ may cause
~R CMD check~ to give a warning warning about unknown ~\Sexpr~ section at top level.
# This warning is not issued at least since R-devel 2018-10-02 r75388.


* Inserting figures/graphs/plots

Figures can be inserted with the help of the standard Rd markup command ~\figure~.  To
generate figures on the fly, package ="Rdpack"= provides the Rd macro ~\insertFig~ which
takes a snipped of R code, evaluates it and inserts the plot produced by it (using
~\figure~).  ~\insertFig~ takes three arguments: a filename, the package name and the code to
evaluate to produce the figure.  For example,
#+BEGIN_EXAMPLE
    \insertFig{cars.png}{mypackage}{x <- cars$speed; y <- cars$dist; plot(x,y)}
#+END_EXAMPLE
will evaluate the code, save the graph in file ~"man/figures/cars.png"~ subdirectory of
package ~"mypackage"~, and include the figure using ~\figure~. 

See vignette [[https://github.com/GeoBosh/Rdpack/blob/master/vignettes/Inserting_figures_and_evaluated_examples.pdf][=Inserting_figures_and_evaluated_examples=]] for more details.

* Versions of Rdpack

Versions of ~Rdpack~ on Github are almost always fully functional (at least
passing =R CMD check --as-cran=), and so use a three-part version number. If a
version is really unstable, I would use the conventional fourth part
=.9000=. For release on CRAN, the version is incremented to
=x.x.0=[fn:versions].

Note that if ~Rdpack (>= x.x.0)~ is required, it can be abbreviated to 
~Rdpack (>= x.x)~. 

[fn:versions] I adopted this versionning scheme from ~Rdpack 0.7.0~.

